default: &default
  adapter: postgresql
  pool: <%= ENV["PG_POOL"] { 5 } %>
  timeout: 5000
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>

development:
  <<: *default
  database: playpart_development

test:
  <<: *default
  database: playpart_test

production:
  <<: *default
  database: playpart_production
  password: <%= ENV["PG_PASSWORD"] %>
